@startuml Models

hide empty methods
hide circle

class User {
    id: uuid
    email: string
    name: string
    password_digest: string
}

class Post {
    id: uuid
    text: string
    created_on: DateTime
}

Post "*" --* User: author
Post "*" --* Post: parent

class Like {
    id: uuid
    emotion: string
}

Like "*" --* User
Like "*" --* Post

@enduml
