@startuml SchemaQuery

@startmindmap

* Query
**[#orange] users: [User!]! ⇢
**[#lightgreen] user(id: ID, email: String): User! ⇢
***[#lightblue] id: ID!
***[#lightblue] email: String!
***[#lightblue] name: String!
***[#orange] posts: [Post]! ⇢
***[#orange] reactions: [Reaction!]! ⇢
**[#lightgreen] me: User ⇢
**[#orange] posts: [Post!]! ⇢
**[#lightgreen] post(id: ID!): Post!
***[#lightblue] id: ID!
***[#lightgreen] author: User! ⇢
***[#lightgreen] parent: Post ⇢
***[#lightblue] text: String!
***[#lightblue] createdAt: ISO8601DateTime!
***[#orange] comments: [Message!]! ⇢
***[#orange] reactions: [Reaction!]! ⇢
****[#lightblue] id: ID!
****[#lightblue] emotion: Emotion!
*****_ LIKE
*****_ DISLIKE
*****_ LOVE
*****_ LAUGH
*****_ CRY
*****_ WOW
****[#lightblue] createdAt: ISO8601DateTime!
****[#lightgreen] post: Post! ⇢
****[#lightgreen] user: User! ⇢

legend top left
  Green: Object
  Orange: Arrays of objects
  Blue Scalar or Arrays of scalars
  ⇢: Repeats an already defined element in the graph
endlegend

@endmindmap

@enduml
