@startuml SchemaMutations

@startmindmap

* Mutations
** logIn
***_:Sets a user ID in the session cookie,
so all other mutations are authenticated;
*** Arguments:
**** email: String!
**** password: String!
*** Fields:
**** user: User (null if login fails)
** logOut
***_:Clears the user ID from session cookie,
so further mutations are not authenticated;
** createUser
*** Arguments:
**** email: String!
**** name: String!
**** password: String!
*** Fields:
**** user: User!
** updateUser
*** Arguments:
**** id: ID!
**** email: String
**** name: String
**** password: String
*** Fields:
**** user: User!
** deleteUser
*** Arguments:
**** id: ID!
*** Fields:
**** user: User!
** createPost
*** Arguments:
**** text: String!
**** parent_id: ID
*** Fields:
**** post: Post!
** deletePost(id: ID)
** likePost(postId: ID)
** unlikePost(postId: ID)

@endmindmap

@enduml
