@startuml SchemaMutations

@startmindmap

* Mutations
** logIn(userId: ID)
***_:Sets a session cookie, so all
other mutations are authenticated;
** logOut
***_:Clears the session cookie, so
further mutations are not authenticated;
** createUser
*** Arguments:
**** email: String!
**** name: String!
**** password: String!
*** Fields:
**** user: User!
** updateUser
*** Arguments:
**** id: ID!
**** email: String
**** name: String
**** password: String
*** Fields:
**** user: User!
** deleteUser
*** Arguments:
**** id: ID!
*** Fields:
**** user: User!
** createPost(...)
** deletePost(id: ID)
** likePost(postId: ID)
** unlikePost(postId: ID)

@endmindmap

@enduml
