@startuml SchemaQuery

@startmindmap

* Query
**[#orange] users: [User] ⇢
**[#lightgreen] user(id: ID): User ⇢
***[#lightblue] id: ID
***[#lightblue] name: string
***[#orange] posts: [Post] ⇢
***[#orange] reactionss: [Reaction] ⇢
**[#orange] posts: [Post] ⇢
**[#lightgreen] post(id: ID): Post
***[#lightblue] id: ID
***[#lightblue] text: string
***[#lightblue] createdOn: DateTime
***[#lightgreen] author: User ⇢
***[#orange] comments: [Message] ⇢
***[#orange] reactions: [Reaction] ⇢
**[#lightgreen] reaction(id: ID): Reaction
***[#lightblue] id: ID
***[#lightblue] emotion: Emotion
****_ LIKE
****_ DISLIKE
****_ LOVE
****_ LAUGH
****_ CRY
****_ WOW
***[#lightgreen] message: Message ⇢
***[#lightgreen] user: User ⇢

legend top left
  Green: Object
  Orange: Arrays of objects
  Blue Scalar or Arrays of scalars
  ⇢: Repeats an already defined element in the graph
endlegend

@endmindmap

@enduml
