version: '3'

name: graphql_example-java_spring

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 30201
    volumes:
      - ../../../..:/workspaces:cached
    command: sleep infinity
    network_mode: host

  postgres:
    image: postgres:15.1
    restart: unless-stopped
    ports:
      - 30202:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres-data:
