#!/usr/bin/env sh

if tmux has-session -t Examples; then
    echo "tmux session Examples already exists"
else
    echo "Starting tmux session Examples"
    tmux new-session -d -s Examples
fi

for exampleDirectory in `find /workspaces/graphql_examples/examples -mindepth 1 -maxdepth 1 -type d`; do
    exampleName=$(basename $exampleDirectory)
    echo "Starting in tmux the initial setup for $exampleName"
    tmux new-window -t Example -n $exampleName -c $exampleDirectory "./initial_setup;/usr/bin/zsh"
done
