#!/usr/bin/sh

# This script runs as user `vscode`.
echo "I am $USER, executing in $PWD"

echo Setting ZSH as default shell
sudo chsh --shell /usr/bin/zsh vscode

echo Setting default ZSH theme
sed -i -e 's/^ZSH_THEME=.*/ZSH_THEME="amuse"/' ~/.zshrc

echo "Updating & Upgrading Packages"
sudo apt update
sudo apt upgrade -y

echo "Installing additional packages"
sudo apt install -y libpq-dev tmux

echo "Starting PostgreSQL Server"
sudo service postgresql start

# echo Installing base JS/TS dependencies
yarn install

# echo "Launching background initializations --> tmux attach -t Examples"
.devcontainer/examples_inits
