#!/usr/bin/env ruby
tmux_session = "Examples"

def cmd(*cmd_parts)
  return if system(cmd_parts.join(" "))
  puts "\nFailed to execute command:"
  puts cmd_parts.join(" ")
  exit 1
end

unless system("tmux has-session -t #{tmux_session}")
  # `tmux has-session` will exit with an error if the session does not exist.
  puts "starting tmux session #{tmux_session}"
  cmd("tmux new-session -s #{tmux_session} -d")
end

examples = Dir["/workspaces/graphql_examples/examples/*"]
  .filter { File.directory? _1 }
  .map { _1.delete_prefix "/workspaces/graphql_examples/examples/" }

examples.each do |example|
  cmd(
    "tmux new-window",
    "-t #{tmux_session}",
    "-n #{example}",
    "-c /workspaces/graphql_examples/examples/#{example}",
    '"./initial_setup;/usr/bin/zsh"'
  )
end
