source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

# Core & Database & Serialization
gem 'rails', '~> 6.0.3', '>= 6.0.3.3'
gem 'puma', '~> 4.1'
gem 'pg', '>= 0.18', '< 2.0'
gem "active_record_extended"
gem 'redis', '~> 4.0'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.2', require: false
gem "oj"

# GraphQL
gem "graphql"
gem "graphiql-rails"
gem "graphql-rails_logger"
gem "graphql-batch"

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec-rails"
  gem "guard"
  gem "guard-rspec"
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rescue"
  gem "pry-stack_explorer"
  gem "bullet"
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "annotate"
  gem "pry-rails"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
