#!/usr/bin/bash
echo ""
echo "Install Bundle Packages"
bundle install
echo ""
echo "Setup Rails Database"
bin/rails db:setup db:migrate db:fixtures:load
echo ""
echo "To start developping:"
echo "bin/rails s"
echo ""
