package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"

	"github.com/adeynack/graphql_examples/examples/go/graph"
	"github.com/adeynack/graphql_examples/examples/go/graph/model"
)

// ID is the resolver for the id field.
func (r *reactionResolver) ID(ctx context.Context, obj *model.Reaction) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Reaction returns graph.ReactionResolver implementation.
func (r *Resolver) Reaction() graph.ReactionResolver { return &reactionResolver{r} }

type reactionResolver struct{ *Resolver }
