version: '3'

name: graphql_example-rails

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 30001
    volumes:
      - ../../../..:/workspaces:cached
    command: sleep infinity
    network_mode: host

  postgres:
    image: postgres:15.1
    restart: unless-stopped
    ports:
      - 30002:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres-data:
