name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  'examples-tests':
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and run dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: yarn test
